# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_BCMDHD)	+= rkwifi/
obj-$(CONFIG_CYW_BCMDHD)	+= cywdhd/
obj-$(CONFIG_INFINEON_DHD)	+= infineon/
obj-$(CONFIG_RTL8723DU) += rtl8723du/
obj-m += aic8800/
obj-m += aic_btusb/
